### ISSUE TITLE
Zero values on Total Production leads to wrong energy counting

### ISSUE THREAD

**Issue by birdie1** [StephanJoubert/home_assistant_solarman#111]
I have a Deye SUN600G3. I am using the inverter_definition deye_string.yml. When the inverter starts in the morning the "Total Production" get a zero value. Because it is from class total_increasing this leads to totally wrong values in energy counting.

It probably should give no data instead of zero values on sensors with class total_increasing.

![image](https://user-images.githubusercontent.com/33814912/194643629-0e1620b4-6bdb-448b-b4a0-d87c8a679eb5.png)
![image](https://user-images.githubusercontent.com/33814912/194643696-9ba76e55-ced9-4677-8e46-389b5e01ac3c.png)

**Comment by rolandsteinmeyer** [comment]
see issue #66

**Comment by birdie1** [comment]
Unfortunately this does not help, as the inverter reports one 0 value after booting in the morning. The problem is not the unknown value. A possible solution would be, that a type "total_increasing" value should never be allowed to be zero.

**Comment by alienatedsec** [comment]
#122 #120 hopefully #125 can fix this

**Comment by chawawa** [comment]
> #122 #120 hopefully #125 can fix this

Thank for the update. Will add the code and see how it does. Lets hope this gets merged into the main code.

**Comment by alienatedsec** [comment]
> > #122 #120 hopefully #125 can fix this
> 
> 
> 
> Thank for the update. Will add the code and see how it does. Lets hope this gets merged into the main code.
@chawawa  how it went for you? Mine is still the same

**Comment by Panoramiac** [comment]
I guess I have the same issue. Each morning, I have a peak in the energy dashboard, which makes no sense. Here is my graph: 
![image](https://user-images.githubusercontent.com/48438802/201597427-1e102b68-d082-4a78-a832-8a96cfbd901c.png)

I am currently removing this peak with the statistics correction tool in the developer tools...

**Comment by bbjunkie** [comment]
``` availability: "{{ 10 < states('sensor.solis_total_energy_exported')|float(0) < 20000  }}" ```

This appears to work for me in HACS, limits it to values above 10 and below 20000

Need a proper fix though as its just a kludge

**Comment by Panoramiac** [comment]
> availability: "{{ 10 < states('sensor.solis_total_energy_exported')|float(0) < 20000 }}"

Thanks!
Is this a part of a template sensor or where to put that?

**Comment by bbjunkie** [comment]
Yes, drop it in the template On 16 Nov 2022, at 14:49, Tobias ***@***.***> wrote:﻿

availability: "{{ 10 < states('sensor.solis_total_energy_exported')|float(0) < 20000 }}"

Thanks!
Is this a part of a template sensor or where to put that?

**Comment by bbjunkie** [comment]
> > availability: "{{ 10 < states('sensor.solis_total_energy_exported')|float(0) < 20000 }}"
> 
> Thanks! Is this a part of a template sensor or where to put that?

Yes, drop it in the template 👇

`- sensor:
    - name: "Filtered Total Energy Exported"
      icon: mdi-counter
      unit_of_measurement: "kWh"
      state: "{{ states('sensor.solis_total_energy_exported')|float(0) }}"

      availability: "{{ 10 < states('sensor.solis_total_energy_exported')|float(0) < 700  }}"
      device_class: energy
      state_class: "total_increasing"`
