### ISSUE TITLE
Solarman reports incorrect values occasionally

### ISSUE THREAD

**Issue by PeterHanusiak** [StephanJoubert/home_assistant_solarman#146]
Hi Folks,

I guess solarman addon has a weird bug on my system with Deye SUN-5K-SG03LP1-EU. On average once a day it reports some completely crazy values.
For example it tells me that I am offgrid, PV1 power has 1000W, PV2 power has 0W, SOC is 0%, Grid voltage jumps to 1280V, Total Grid power is 5644W and basically almost every sensor shows some crazy values. Please have a look at my graphs.
I found another user from a different country, who has exactly the same problem, so I don't think it is actually real what solarman is showing. Anyway my Deye behaves perfectly ok, and there are no alarms. So that's why I believe that this is not real, it is just solarman crazy.

Please let me know if you are aware of this and if there is a way to fix it.

Thank you
Peter
![grid_peak](https://user-images.githubusercontent.com/96705792/205932295-9ead3be2-c6f5-425d-9321-1607111ec69c.png)
![grid_voltage](https://user-images.githubusercontent.com/96705792/205932303-9af3bc26-2d7b-422b-a330-76548e52a9d0.png)
![pv_peak](https://user-images.githubusercontent.com/96705792/205932304-89628367-4a69-438d-8365-3201768c1c2f.png)
![battery_soc](https://user-images.githubusercontent.com/96705792/205932308-501f01d4-7ba1-4bd4-afae-9525446fdd56.png)
![blackout](https://user-images.githubusercontent.com/96705792/205932310-2613882c-1d8b-4655-ab31-57bbb261d3f1.png)

**Comment by PV-Joe** [comment]
Hi Peter,

my DEYE SUN-8K-SG04LP3-EU is working flawlessly with the following optimized **"deye_hybrid.yaml"**
Replace the following code and restart Home Assistant.
Good luck and hope this helps.

`# File: deye_hybrid.yaml for Solarman Addon in Home Assistant 2022-11
# DEYE SUN 5-12K EU Hybrid Inverter
# DEYE SUN-8K-SG04LP3-EU | 8KW | Three Phase | 2 MPPT | Hybrid Inverter | Low Voltage Battery
# Modbus information retrieved from: Deye Modbus RTU tree Phase Energy Storage Communications Protokoll
# Initial registers by wendtc | additional registers by Ondrej Bartas | edited by PV-Joy
# working with: Wifi.Logger LSW3_15_FFFF_1.0.91R | Extended System Version：V1.1.00.0F
# SUN-8K-SG04LP3-EU | Protocol Version：0104 | MAIN：2005-1121-1807 | HMI：0-1001-c030


requests:
  - start: 0x0003
    end: 0x0059
    mb_functioncode: 0x03
  - start: 0x01F4
    end: 0x01F5
    mb_functioncode: 0x03  
  - start: 0x0204  
    end: 0x0217
    mb_functioncode: 0x03
  - start: 0x021C  
    end: 0x021D
    mb_functioncode: 0x03
  - start: 0x0229  
    end: 0x022E
    mb_functioncode: 0x03    
  - start: 0x024A  
    end: 0x024F
    mb_functioncode: 0x03  
  - start: 0x0256  
    end: 0x025F
    mb_functioncode: 0x03 
  - start: 0x0260  
    end: 0x026A
    mb_functioncode: 0x03
  - start: 0x0271
    end: 0x027C
    mb_functioncode: 0x03    
  - start: 0x0284  
    end: 0x028D
    mb_functioncode: 0x03   
  - start: 0x02A0  
    end: 0x02A7
    mb_functioncode: 0x03 
  - start: 0x0085  
    end: 0x0085
    mb_functioncode: 0x03 
  
parameters:
 - group: solar
   items: 
    - name: "PV1 Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 1
      registers: [0x02A0]
      icon: 'mdi:solar-power'

    - name: "PV2 Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 1
      registers: [0x02A1]
      icon: 'mdi:solar-power'

    - name: "PV1 Voltage"
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x02A4]
      icon: 'mdi:solar-power'

    - name: "PV2 Voltage"
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x02A6]
      icon: 'mdi:solar-power'

    - name: "PV1 Current"
      class: "current"
      state_class: "measurement"
      uom: "A"
      scale: 0.1
      rule: 1
      registers: [0x02A5]
      icon: 'mdi:solar-power'

    - name: "PV2 Current"
      class: "current"
      state_class: "measurement"
      uom: "A"
      scale: 0.1
      rule: 1
      registers: [0x02A7]
      icon: 'mdi:solar-power'

    - name: "Daily Production"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [0x0211]
      icon: 'mdi:solar-power'

    - name: "Total Production"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 3
      registers: [0x0216,0x0217]
      icon: 'mdi:solar-power'

 - group: Battery
   items: 
    - name: "Total Battery Charge"
      class: "energy"
      state_class: "total_increasing"      
      uom: "kWh"
      scale: 0.1
      rule: 3
      registers: [0x0204,0x0205]
      icon: 'mdi:battery-plus'

    - name: "Total Battery Discharge"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 3
      registers: [0x0206,0x0207]
      icon: 'mdi:battery-minus'

    - name: "Battery Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x024E]
      icon: 'mdi:battery'

    - name: "Battery Voltage"
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.01
      rule: 1
      registers: [0x024B]
      icon: 'mdi:battery'

    - name: "Battery SOC"
      class: "battery"
      state_class: "measurement"
      uom: "%"
      scale: 1
      rule: 1
      registers: [0x024C]
      icon: 'mdi:battery'

    - name: "Battery Current"
      class: "current"
      state_class: "measurement"
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x024F]
      icon: 'mdi:battery'

    - name: "Battery Temperature"
      class: "temperature"
      state_class: "measurement"
      uom: "°C"
      scale: 0.1
      rule: 1
      offset: 1000      
      registers: [0x024A]
      icon: 'mdi:battery'
 
 - group: Grid
   items: 
    - name: "Total Grid Power"
      class: "measurement"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x0271]
      icon: 'mdi:transmission-tower'

    - name: "Grid Voltage L1"
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0256]
      icon: 'mdi:transmission-tower'

    - name: "Grid Voltage L2"
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0257]
      icon: 'mdi:transmission-tower'
      
    - name: "Grid Voltage L3"
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0258]
      icon: 'mdi:transmission-tower'  

    - name: "Internal CT L1 Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x025C]
      icon: 'mdi:transmission-tower'

    - name: "Internal CT L2 Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x025D]
      icon: 'mdi:transmission-tower'
      
    - name: "Internal CT L3 Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x025E]
      icon: 'mdi:transmission-tower'  

    - name: "External CT L1 Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x0268]
      icon: 'mdi:transmission-tower'

    - name: "External CT L2 Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x0269]
      icon: 'mdi:transmission-tower'
      
    - name: "External CT L3 Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x026A]
      icon: 'mdi:transmission-tower'
      
    - name: "Daily Energy Bought"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [0x0208]
      icon: 'mdi:transmission-tower-export'

    - name: "Total Energy Bought"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [0x020A,0x020B]
      icon: 'mdi:transmission-tower-export'
      
    - name: "Daily Energy Sold"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [0x0209]
      icon: 'mdi:transmission-tower-import'

    - name: "Total Energy Sold"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 3
      registers: [0x020C,0x020D]
      icon: 'mdi:transmission-tower-import'

    - name: "Total Grid Production"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 4
      registers: [0x020C,0x020D]
      icon: 'mdi:transmission-tower'
      
 - group: Upload
   items: 
    - name: "Total Load Power"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 1
      rule: 1
      registers: [0x028D]
      icon: 'mdi:lightning-bolt-outline'

    - name: "Load L1 Power"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 1
      rule: 1
      registers: [0x028A]
      icon: 'mdi:lightning-bolt-outline'

    - name: "Load L2 Power"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 1
      rule: 1
      registers: [0x028B]
      icon: 'mdi:lightning-bolt-outline'
      
    - name: "Load L3 Power"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 1
      rule: 1
      registers: [0x028C]
      icon: 'mdi:lightning-bolt-outline'
      
    - name: "Load Voltage L1"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0284]
      icon: 'mdi:lightning-bolt-outline'
      
    - name: "Load Voltage L2"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0285]
      icon: 'mdi:lightning-bolt-outline'
      
    - name: "Load Voltage L3"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0286]
      icon: 'mdi:lightning-bolt-outline'
      
    - name: "Daily Load Consumption"
      class: "energy"
      state_class: "total_increasing"      
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [0x020E]
      icon: 'mdi:lightning-bolt-outline'

    - name: "Total Load Consumption"
      class: "energy"
      state_class: "total_increasing"      
      uom: "kWh"
      scale: 0.1
      rule: 3
      registers: [0x020F,0x0210]
      icon: 'mdi:lightning-bolt-outline'

    - name: "SmartLoad Enable Status"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x00C3]
      isstr: true
      lookup: 
      -  key: 0
         value: "OFF"
      -  key: 1
         value: "ON"
      icon: 'mdi:lightning-bolt-outline'
     
 - group: Inverter
   items: 
    - name: "Running Status"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x01F4]
      isstr: true
      lookup: 
      -  key: 0
         value: "Stand-by"
      -  key: 1
         value: "Self-checking"
      -  key: 2
         value: "Normal"
      -  key: 3
         value: "FAULT"
      icon: 'mdi:home-lightning-bolt'

    - name: "Total Power"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x00AF]
      icon: 'mdi:home-lightning-bolt'

    - name: "Current L1"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x0276]
      icon: 'mdi:home-lightning-bolt'

    - name: "Current L2"
      class: "current"
      state_class: "measurement"
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x0277]
      icon: 'mdi:home-lightning-bolt'
      
    - name: "Current L3"
      class: "current"
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x0278]
      icon: 'mdi:home-lightning-bolt'
      
    - name: "Inverter L1 Power"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x0279]
      icon: 'mdi:home-lightning-bolt'

    - name: "Inverter L2 Power"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x027A]
      icon: 'mdi:home-lightning-bolt'
      
    - name: "Inverter L3 Power"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 1
      rule: 2
      registers: [0x027B]
      icon: 'mdi:home-lightning-bolt'
      
    - name: "DC Temperature"
      class: "temperature"
      state_class: "measurement"      
      uom: "°C"
      scale: 0.1
      rule: 2
      offset: 1000      
      registers: [0x021C]
      icon: 'mdi:thermometer'

    - name: "AC Temperature"
      class: "temperature"
      state_class: "measurement"      
      uom: "°C"
      scale: 0.1
      rule: 2
      offset: 1000      
      registers: [0x021D]
      icon: 'mdi:thermometer'

    - name: "Inverter ID"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 5
      registers: [0x0003,0x0004,0x0005,0x0006,0x0007]
      isstr: true
    
    - name: "Communication Board Version No."
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0011]
      isstr: true

    - name: "Control Board Version No."
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x000D]
      isstr: true

 - group: Alert
   items: 
    - name: "Alert"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 6
      registers: [0x0229,0x022A,0x22B,0x022C,0x022D,0x022E]`
      

[deye_hybrid.yaml.txt](https://github.com/StephanJoubert/home_assistant_solarman/files/10169770/deye_hybrid.yaml.txt)

**Comment by PeterHanusiak** [comment]
Hi PV-Joe,

Unfortunately your setup uses completely different registers than mine. So now all my sensors have unknown values. Actually my config is OK, it just happens like once a day that I get some crazy values. I guess config is OK, it must be something else that is causing it.

Check my config:
[deye_hybrid.yaml_moj_deye.txt](https://github.com/StephanJoubert/home_assistant_solarman/files/10170824/deye_hybrid.yaml_moj_deye.txt)

**Comment by vinaytje94** [comment]
Hello everyone,

Peter was talking about me. I have the same issues. Everything is fine with the inverter when it happens. System shows offgrid with all the other weird readings then goes to normal after the next minute update.
I have a single Deye SUN-8K-SG01LP1-US inverter sn 21xxx with LSW3 logger with sn 23xx and FW LSW3_15_FFFF_1.0.72
What could be the issue?

Also the configuration profile of PV-Joe does not work with mine. 
![Screenshot (3)](https://user-images.githubusercontent.com/110492139/206244801-27bb7d27-8c26-4aa1-bfe0-15bf8575edab.png)

**Comment by PeterHanusiak** [comment]
Hi,

Since I initially reported this issue I will propose to close it. After a couple of updates of HA core, HACS and even firmware update of my wifi dongle I don't see this problem anymore. So it looks to me that this is not related to the solarman addon. It was most likely caused by the HA or wifi dongle. Difficult for me to prove it, but there are a couple of days when I don't see this data problem, while before it happened on average once a day.
If anyone experiences it, feel free to reopen it.

Peter
