### ISSUE TITLE
SofarSolar unknown data in entities

### ISSUE THREAD

**Issue by kion666** [StephanJoubert/home_assistant_solarman#18]
Hi @StephanJoubert and thanks for this nice integration. I have an SofarSolar  and it looks very similar as DEYE. It is now connected to solarman. But I have some problems with integration in HA. All the data are unknown

![image](https://user-images.githubusercontent.com/62517382/153217271-3404cbff-515c-4f62-82b7-526070dfda52.png)

![image](https://user-images.githubusercontent.com/62517382/153217420-f8455049-a2c9-419a-848d-87835debaf89.png)

Can You support me in that case?  Thanks in advance

**Comment by StephanJoubert** [comment]
I have created a yaml file from the data I have. It was not possible to test at all so please expect problems :) See attached zipfile.

To test. 
1. Make a copy of parameters.yaml  in the custom_components/solarman folder
2. Overwrite parameters.yaml with the file parameters_sofar.yaml. (Rename parameters_sofar.yaml to parameters.yaml) 
3. See if you get any success, and if so, which parameters need tweaking.

I include the file I used as source to get the parameter definition SOFARMap.txt and the yaml file generated from it that you can use as starting point.

[lookup_files.zip](https://github.com/StephanJoubert/home_assistant_solarman/files/8035192/lookup_files.zip)

**Comment by kion666** [comment]
Thank you very much Stephan. I will try to test it tomorrow morning (now my child's are going sleep)  and of course I will let you know. I really appreciate your help.

**Comment by kion666** [comment]
Hi @StephanJoubert. I just checked HA and I can see that some of the data are not correct like daily and  total production. I checked the paramaters.yaml and SofarMAE.txt and it looks like the registers are the same.  Some of entities are not neccesary in my inverter, but I cane remove them myself :) But I don't now what to do with wrong daily, total production and  time.
Other parameters are shown correctly like power/voltage.
![image](https://user-images.githubusercontent.com/62517382/153378132-ed1e12fc-e9a5-47f2-b614-9f4f211804f6.png)

Thanks in advance.

**Comment by grzegorz189** [comment]
- name: "Total Production"
      class: "energy"
      uom: "kWh"
      scale: 1
      rule: 3
      registers: [0x0016,0x0015]
      icon: 'mdi:solar-power'      

    - name: "Total generation time"
      class: ""
      uom: "h"
      scale: 1
      rule: 3
      registers: [0x0018,0x0017]
      icon: 'mdi:clock-outline'

**Comment by grzegorz189** [comment]
<img width="379" alt="Zrzut ekranu 2022-02-10 144157" src="https://user-images.githubusercontent.com/17804684/153419932-3641f637-c3ab-4fa6-b933-b7147c866b2b.png">

**Comment by grzegorz189** [comment]
requests:
  - start: 0x0000
    end:  0x0027
  - start: 0x0105
    end: 0x0114


parameters:
 - group: solar
   items: 
    - name: "PV1 Power"
      class: "power"
      uom: "W"
      scale: 10
      rule: 1
      registers: [0x000A]
      icon: 'mdi:solar-power'

    - name: "PV2 Power"
      class: "power"
      uom: "W"
      scale: 10
      rule: 1
      registers: [0x000B]
      icon: 'mdi:solar-power'

    - name: "PV1 Voltage"
      class: "voltage"
      uom: "V"
      scale: 0.1
      rule: 1 
      registers: [0x0006]
      icon: 'mdi:solar-power'

    - name: "PV2 Voltage"
      class: "voltage"    
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0008]
      icon: 'mdi:solar-power'      

    - name: "PV1 Current"
      class: "current"
      uom: "A"
      scale: 0.01
      rule: 1
      registers: [0x0007]
      icon: 'mdi:solar-power'      

    - name: "PV2 Current"
      class: "current"
      uom: "A"
      scale: 0.01
      rule: 1
      registers: [0x0009]
      icon: 'mdi:solar-power'      

    - name: "Daily Production"
      class: "energy"
      uom: "kWh"
      scale: 0.01
      rule: 1
      registers: [0x0019]
      icon: 'mdi:solar-power'      

    - name: "Total Production"
      class: "energy"
      uom: "kWh"
      scale: 1
      rule: 3
      registers: [0x0016,0x0015]
      icon: 'mdi:solar-power'      

    - name: "Total generation time"
      class: ""
      uom: "h"
      scale: 1
      rule: 3
      registers: [0x0018,0x0017]
      icon: 'mdi:clock-outline'   

    - name: "Today generation time"
      class: ""
      uom: "min"
      scale: 1
      rule: 1
      registers: [0x001A]
      icon: 'mdi:clock-outline'      

 - group: Output
   items: 
    - name: "Output active power"
      class: "power"
      uom: "W"
      scale: 10
      rule: 1
      registers: [0x000C]
      icon: 'mdi:home-lightning-bolt'

    - name: "Output reactive power"
      class: ""
      uom: "kVar"
      scale: 0.01
      rule: 1
      registers: [0x000D]
      icon: 'mdi:home-lightning-bolt'

    - name: "Grid frequency"
      class: "frequency"
      uom: "Hz"
      scale: 0.01
      rule: 1
      registers: [0x000E]
      icon: 'mdi:home-lightning-bolt'

    - name: "L1 Voltage"
      class: "voltage"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x000F]
      icon: 'mdi:home-lightning-bolt'

    - name: "L1 Current"
      class: "current"
      uom: "A"
      scale: 0.01
      rule: 1
      registers: [0x0010]
      icon: 'mdi:home-lightning-bolt'

    - name: "L2 Voltage"
      class: "voltage"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0011]
      icon: 'mdi:home-lightning-bolt'

    - name: "L2 Current"
      class: "current"
      uom: "A"
      scale: 0.01
      rule: 1
      registers: [0x0012]
      icon: 'mdi:home-lightning-bolt'

    - name: "L3 Voltage"
      class: "voltage"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0013]
      icon: 'mdi:home-lightning-bolt'

    - name: "L3 Current"
      class: "current"
      uom: "A"
      scale: 0.01
      rule: 1
      registers: [0x0014]
      icon: 'mdi:home-lightning-bolt'

 - group: Inverter
   items: 
    - name: "Inverter status"
      class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0000]
      lookup: 
      -  key: 0
         value: "Stand-by"
      -  key: 1
         value: "Self-checking"
      -  key: 2
         value: "Normal"
      -  key: 3
         value: "FAULT"
      -  key: 4
         value: "Permanent"
      icon: 'mdi:wrench'         

    - name: "Inverter module temperature"
      class: "temperature"
      uom: "°C"
      scale: 1
      rule: 1
      registers: [0x001B]
      icon: 'mdi:thermometer'

    - name: "Inverter inner temperature"
      class: "temperature"
      uom: "°C"
      scale: 1
      rule: 1
      registers: [0x001C]
      icon: 'mdi:thermometer'      

    - name: "Inverter bus voltage"
      class: "voltage"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x001D]
      icon: 'mdi:home-lightning-bolt'

    - name: "PV1 voltage sample by slave CPU"
      class: "voltage"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x001E]
      icon: 'mdi:home-lightning-bolt'

    - name: "PV1 current sample by slave CPU"
      class: "current"
      uom: "A"
      scale: 0.1
      rule: 1
      registers: [0x001F]
      icon: 'mdi:home-lightning-bolt'

    - name: "Countdown time"
      class: ""
      uom: "s"
      scale: 1
      rule: 1
      registers: [0x0020]
      icon: ''

    - name: "Inverter alert message"
      class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0021]
      icon: ''

    - name: "Input mode"
      class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0022]
      icon: ''

    - name: "Communication Board inner message"
      class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0023]
      icon: ''

    - name: "Insulation of PV1+ to ground"
      class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0024]
      icon: ''

    - name: "Insulation of PV2+ to ground"
      class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0025]
      icon: ''

    - name: "Insulation of PV- to ground"
      class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0026]
      icon: ''

    - name: "Country"
      class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0027]
      lookup: 
      -  key: 0
         value: "Germany"
      -  key: 1
         value: "CEI0-21 Internal"
      -  key: 2
         value: "Australia"
      -  key: 3
         value: "Spain RD1699"
      -  key: 4
         value: "Turkey"
      -  key: 5
         value: "Denmark"
      -  key: 6
         value: "Greece"
      -  key: 7
         value: "Netherland"
      -  key: 8
         value: "Belgium"
      -  key: 9
         value: "UK-G59"
      -  key: 10
         value: "China"
      -  key: 11
         value: "France"
      -  key: 12
         value: "Poland"
      -  key: 13
         value: "Germany BDEW"
      -  key: 14
         value: "Germany VDE0126"
      -  key: 15
         value: "Italy CEI0-16"
      -  key: 16
         value: "UK-G83"
      -  key: 17
         value: "Greece Islands"
      -  key: 18
         value: "EU EN50438"
      -  key: 19
         value: "EU EN61727"
      -  key: 20
         value: "Korea"
      -  key: 21
         value: "Sweden"
      -  key: 22
         value: "Europe General"
      -  key: 23
         value: "CEI0-21 External"
      -  key: 24
         value: "Cyprus"
      -  key: 25
         value: "India"
      -  key: 26
         value: "Philippines"
      -  key: 27
         value: "New Zeland"
      -  key: 28
         value: "Reserve"
      -  key: 29
         value: "Reserve"
      icon: ''


 - group: Alert
   items: 
    - name: "Fault 1"
      class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0001]
      lookup: 
      -  key: 0
         value: "No error"
      -  key: 1
         value: "ID01 Grid Over Voltage Protection"
      -  key: 2
         value: "ID02 Grid Under Voltage Protection"
      -  key: 4
         value: "ID03 Grid Over Frequency Protection"
      -  key: 8
         value: "ID04 Grid Under Frequency Protection"
      -  key: 16
         value: "ID05 PV Under Voltage Protection"
      -  key: 32
         value: "ID06 Grid Low Voltage Ride through"
      -  key: 64
         value: "ID07"
      -  key: 128
         value: "ID08"
      -  key: 256
         value: "ID09 PV Over Voltage Protection"
      -  key: 512
         value: "ID10 PV Input Current Unbalanced"
      -  key: 1024
         value: "ID11 PV Input Mode wrong configuration"
      -  key: 2048
         value: "ID12 Ground-Fault circuit interrupters fault"
      -  key: 4096
         value: "ID13 Phase sequence fault"
      -  key: 8192
         value: "ID14 Hardware boost over current protection"
      -  key: 16384
         value: "ID15 Hardware AC over current protection"
      -  key: 32768
         value: "ID16 Grid current is too high"
      icon: 'mdi:wrench'  

    - name: "Fault 2"
      class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0002]
      lookup: 
      -  key: 0
         value: "No error"
      -  key: 1
         value: "ID17 Grid current sampling error"
      -  key: 2
         value: "ID18 DCI sampling error"
      -  key: 4
         value: "ID19 Grid voltage sampling error"
      -  key: 8
         value: "ID20 GFCI device sampling error"
      -  key: 16
         value: "ID21 Main chip fault"
      -  key: 32
         value: "ID22 Hardware auxiliary power fault"
      -  key: 64
         value: "ID23 Bus voltage zero fault"
      -  key: 128
         value: "ID24 Output current not balanced"
      -  key: 256
         value: "ID25 Bus under voltage protection"
      -  key: 512
         value: "ID26 Bus over voltage protection"
      -  key: 1024
         value: "ID27 Bus voltage unbalanced"
      -  key: 2048
         value: "ID28 DCI is too high"
      -  key: 4096
         value: "ID29 Grid current is too high"
      -  key: 8192
         value: "ID30 Input current is too high"
      -  key: 16384
         value: "ID31"
      -  key: 32768
         value: "ID32"
      icon: 'mdi:wrench'  

    - name: "Fault 3"
      class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0003]
      lookup: 
      -  key: 0
         value: "No error"
      -  key: 1
         value: "ID33 Reserved"
      -  key: 2
         value: "ID34 Reserved"
      -  key: 4
         value: "ID35 Reserved"
      -  key: 8
         value: "ID36 Reserved"
      -  key: 16
         value: "ID37 Reserved"
      -  key: 32
         value: "ID38 Reserved"
      -  key: 64
         value: "ID39 Reserved"
      -  key: 128
         value: "ID40 Reserved"
      -  key: 256
         value: "ID41 Reserved"
      -  key: 512
         value: "ID42 Reserved"
      -  key: 1024
         value: "ID43 Reserved"
      -  key: 2048
         value: "ID44 Reserved"
      -  key: 4096
         value: "ID45 Reserved"
      -  key: 8192
         value: "ID46 Reserved"
      -  key: 16384
         value: "ID47 Reserved"
      -  key: 32768
         value: "ID48 Reserved"
      icon: 'mdi:wrench'  

    - name: "Fault 4"
      class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0004]
      lookup: 
      -  key: 0
         value: "No error"
      -  key: 1
         value: "ID49 Grid voltage sampling value between master and slave DSP vary widely"
      -  key: 2
         value: "ID50 Grid frequency sampling value between master and slave DSP vary widely"
      -  key: 4
         value: "ID51 DCI sampling value between master and slave DSP vary widely"
      -  key: 8
         value: "ID52 GFCI sampling value between master and slave DSP vary widely"
      -  key: 16
         value: "ID53 Communication failure between master and slave DSP failure"
      -  key: 32
         value: "ID53 Communication failure between slave and communication board"
      -  key: 64
         value: "ID55 Relay fault"
      -  key: 128
         value: "ID56 Insulation resistance between PV array and the earth is too low"
      -  key: 256
         value: "ID57 Inverter temp is too high"
      -  key: 512
         value: "ID58 Boost temp is too high"
      -  key: 1024
         value: "ID59 Environment temp is too high"
      -  key: 2048
         value: "ID60 Brak podłączenie falownika do kabla PE"
      -  key: 4096
         value: "ID61 Reserved"
      -  key: 8192
         value: "ID62 Reserved"
      -  key: 16384
         value: "ID63 Reserved"
      -  key: 32768
         value: "ID64 Reserved"
      icon: 'mdi:wrench'  

    - name: "Fault 5"
      class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0005]
      lookup: 
      -  key: 0
         value: "No error"
      -  key: 1
         value: "ID65 Grid current is too high and causes unrecoverable fault"
      -  key: 2
         value: "ID66 Bus voltage is too high and causes unrecoverable fault"
      -  key: 4
         value: "ID67 Grid current is unbalanced and causes unrecoverable fault"
      -  key: 8
         value: "ID68 Input current is unbalanced and causes unrecoverable fault"
      -  key: 16
         value: "ID69 Bus voltage is unbalanced and causes unrecoverable fault"
      -  key: 32
         value: "ID70 Grid current is too high and causes unrecoverable fault"
      -  key: 64
         value: "ID65 PV Input Mode Configuration is wrong and causes unrecoverable fault"
      -  key: 128
         value: "ID72 Reserved"
      -  key: 256
         value: "ID73 Reserved"
      -  key: 512
         value: "ID74 Input current is too high and causes unrecoverable fault"
      -  key: 1024
         value: "ID75 Error reading from EEPROM"
      -  key: 2048
         value: "ID76 Error writing to EEPROM"
      -  key: 4096
         value: "ID77 Relay fauilure causes unrecoverable fault"
      -  key: 8192
         value: "ID78 Reserved"
      -  key: 16384
         value: "ID79 Reserved"
      -  key: 32768
         value: "ID80 Reserved"
      icon: 'mdi:wrench'

**Comment by grzegorz189** [comment]
Very good idea, "state_class" - ok,
I still have a problem with showing the status of history, you can take a look at it
![Przechwytywanie](https://user-images.githubusercontent.com/17804684/154119610-980e6d93-21d2-499d-a1ac-3c175bdf28d9.PNG)
Thanks

**Comment by grzegorz189** [comment]
I have one more problem after restarting home assistant and when the inverter is turned off, most often at night, all entities are unknown
![Przechwytywanie](https://user-images.githubusercontent.com/17804684/154120571-ee3b8e0d-3a3b-4567-ad19-94cd4588d520.PNG)

**Comment by kion666** [comment]
Hi @StephanJoubert  and @grzegorz189 
I will try to check the new config for sofar tomorrow and I will let you know.  Thanks for update state class. Now I have to manually add this to daily and totally production. It will be easier to configure. Best regards

**Comment by StephanJoubert** [comment]
@grzegorz189 Yea the entities will do that if home assistant is restarted while the inverter was offline. However, if the entities has values and the inverter goes offline, the values will be maintained.

If you want to use these in automations and it presents a problem, you should be able to look at the status_connection or status_lastUpdate to determine if the values can be used.

**Comment by kion666** [comment]
Hi once again @StephanJoubert I confirm that after added sofar yaml to configuration.yaml some of the entities ar unavailable. However the most important for me as daily production, Power, Voltage are working ok.

![image](https://user-images.githubusercontent.com/62517382/154248290-1356fa56-7c26-4070-9923-7ac77bf81cb3.png)


Thank You very much for your help.

**Comment by binoke** [comment]
I have a 3Phase invertor (Sofar HYD 10KTL-3PH-A).  I have tested the code and integration in HA.  I see that the connection to my invertor works, but the values are unknown or Unavailable.  Would it be possible to create a parameters file for my invertor.   I'm happy to do myself but my modbus knowledge is non-existing.

**Comment by kion666** [comment]
@binoke Did You add the sofar_lsw3.yaml to Your config and do You have this file in config\custom_components\solarman?  I also have the KTL Sofar and most important entities are working correctly for me.

**Comment by binoke** [comment]
@kion666 What I did was as listed in the original discription:
- Backup original parameters.yaml 
- copy sofar_lsw3.yaml to config\custom_components\solarman
- deleted parameters.yaml and renamed sofar_lsw3.yaml to parameters.yaml 

so when I look at the sensor.  I see it's connected and updating
![image](https://user-images.githubusercontent.com/30434109/154255314-ca03491a-e1fe-4a75-86be-15d9d21f13e7.png)
![image](https://user-images.githubusercontent.com/30434109/154255390-dc75308d-ea2e-4592-872f-5bbd67f8f9cb.png)

but all other sensor values are Unknown or Unavailable.

**Comment by kion666** [comment]
I just set the lookup file as:
![image](https://user-images.githubusercontent.com/62517382/154258163-dfdbfa3a-5528-4b1f-b698-6b9fba194028.png)
And downloaded all repo to solarman:
![image](https://user-images.githubusercontent.com/62517382/154258335-7e177819-bb57-4b71-9712-d1e833292f1e.png)

**Comment by cityslicker99** [comment]
Hi does this help?
[SOFARSOLAR ModBus-RTU Communication Protocol (1).pdf](https://github.com/StephanJoubert/home_assistant_solarman/files/8079826/SOFARSOLAR.ModBus-RTU.Communication.Protocol.1.pdf)
p

**Comment by StephanJoubert** [comment]
Hi @kion666 , that is correct. You can now edit the sofar_lsw3 file to get it working as expected.

**Comment by kion666** [comment]
Thanks once again @StephanJoubert   I close the issue and going to buy you coffee :)
