### ISSUE TITLE
HACs update loosing "main" branch

### ISSUE THREAD

**Issue by hillerpa** [StephanJoubert/home_assistant_solarman#182]
Hello everybody,
after HACs update my solarman somehow switched from main to v1.41 where deye_4mppt.yaml is not released.
Can you please create a new v1.42 with the latest yaml files included so that an hacs update work without any losses.

Thank you very much for the work!

**Comment by StephanJoubert** [comment]
Hi @hillerpa , could you please see if a restart solved the issue. Just updated on my side to 1.4.2 and it looks fine.

**Comment by StephanJoubert** [comment]
Glad you are now up an running.
