### ISSUE TITLE
Listen to event and publish to MQTT

### ISSUE THREAD

**Issue by tuanha2000vn** [StephanJoubert/home_assistant_solarman#2]
![image](https://user-images.githubusercontent.com/2765517/149452817-c4093460-9c79-4e4c-859a-a33acf92809c.png)
It's possible to listen to data change and publish the update via mqtt?

A mqtt publish will give a real-time data instead of 30 second passive querry result in a more precise data.

I'm not sure if it's supported by the inverter-logger, jusk ask for the possibility. Thank for the hard work.

**Comment by StephanJoubert** [comment]
Although the collector can be set-up to update a secondary webhook (main one is solarman), I have tried and don't get any information posted to my server. At this time we are polling at the specified interval so, if we post to MQTT at the same time, the interface will have the same response.

It may be useful to add MQTT for node-red or other integrations so I'm keeping this on my list.
