### ISSUE TITLE
Instruction Update

### ISSUE THREAD

**Issue by McAllstar** [StephanJoubert/home_assistant_solarman#20]
This is more an FYI but I noticed in the instructions the config.yaml refers to the lookup_file: solar_lsw2.yaml however when I looked in the solarman directory the file is called solar_lsw**3**.yaml. not sure if that will cause issues or not.

**Comment by StephanJoubert** [comment]
Thanks for that - updated the readme file

**Comment by McAllstar** [comment]
You’re a machine, Thanks

From: StephanJoubert ***@***.***>
Date: Wednesday, 16 February 2022 at 11:30
To: StephanJoubert/home_assistant_solarman ***@***.***>
Cc: Mc Alister, B. (Brett) ***@***.***>, Author ***@***.***>
Subject: Re: [StephanJoubert/home_assistant_solarman] Instruction Update (Issue #20)
CAUTION - EXTERNAL SENDER - Please be careful when opening links and attachments. Nedbank - IT Information Security Department (ISD)

Thanks for that - updated the readme file

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FStephanJoubert%2Fhome_assistant_solarman%2Fissues%2F20%23issuecomment-1041286922&data=04%7C01%7CBrettM%40Nedbank.co.za%7Cf8618ea59a8647edb72208d9f12ee729%7C0b1d23d810d140938cb7fd0bb32f81e1%7C0%7C0%7C637806006040861633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=I5yaHEJEEja%2FN8nD2OUsxShedDbdhEEFDuBA59r5DF8%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJHBIBCUZRK23JX3W7TH5HDU3NU55ANCNFSM5OQ7VMGA&data=04%7C01%7CBrettM%40Nedbank.co.za%7Cf8618ea59a8647edb72208d9f12ee729%7C0b1d23d810d140938cb7fd0bb32f81e1%7C0%7C0%7C637806006040861633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GAlLCMB18va231EpFL6f9yMTlQAiRajTvpQqfTuXrzU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CBrettM%40Nedbank.co.za%7Cf8618ea59a8647edb72208d9f12ee729%7C0b1d23d810d140938cb7fd0bb32f81e1%7C0%7C0%7C637806006040861633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=z5Pv11eI94psryiTgOr4c2WiGZ6Y7lxPkETcbkODDQk%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CBrettM%40Nedbank.co.za%7Cf8618ea59a8647edb72208d9f12ee729%7C0b1d23d810d140938cb7fd0bb32f81e1%7C0%7C0%7C637806006040861633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=K3Ob3tfZCljWkzlAyC5ah84ifmHkncA4tVpzsIl39eU%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>


********************
Nedbank disclaimer and confidentiality notice:

This email may contain information that is confidential, privileged or otherwise protected from disclosure. If you are not an intended recipient of this email or all or some of the information contained therein, do not duplicate or redistribute it by any means. Please delete it and any attachments and notify the sender that you have received it in error. Unless specifically indicated, this email is neither an offer or a solicitation to buy or sell any securities, investment products or other financial product or service, nor is it an official confirmation of any transaction or an official statement of Nedbank. Any views or opinions presented are solely those of the author and do not necessarily represent those of Nedbank. Nedbank Ltd Reg No 1951/000009/06.

The following link displays the names of the Nedbank Board of Directors and Company Secretary. [http://www.nedbank.co.za/terms/DirectorsNedbank.htm]

If you do not want to click on a link, please type the relevant address in your browser
********************
