### ISSUE TITLE
energy panel stop working

### ISSUE THREAD

**Issue by pepelillo** [StephanJoubert/home_assistant_solarman#21]
I've updated my HASSOS to core version 2022.2.7, and Energy panel stop working. I've read something about a change in the class used to store data but I can not provide much more info as I'm not a developer.
Does anybody found the same issue?

**Comment by StephanJoubert** [comment]
Hi @pepelillo , I have also noticed this a while back, and it is due to a changes in the "state_class" added in HA. I have updated this and added a few features, and just and published a new release 1.2.0 with all the updates.

If you are using HACS is will show the update.
