### ISSUE TITLE
Typo in the deye_string.yaml

### ISSUE THREAD

**Issue by oipatet** [StephanJoubert/home_assistant_solarman#233]
Sorry, my English isn't good.

In the deye_string.yaml (and probably all other definitions with this sensor) is a typo in the word output.

- name: "Total **_Ouput_** AC Power"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 0.1
      rule: 3
      registers: [0x0050,0x0051]
      icon: 'mdi:home-lightning-bolt'

I know I'm in github. But I dont know the code enough. So I'm not sure if I'm allowed to change that and the program will still work.

**Comment by lszeremeta** [comment]
I added pull request. It should work, it's just default name change 🙂

**Comment by lszeremeta** [comment]
I opened a pull request. Changing the default name or description should not break anything 🙂
