### ISSUE TITLE
Serial Number 390

### ISSUE THREAD

**Issue by K3vb3rt** [StephanJoubert/home_assistant_solarman#237]
Hey guys,

i have freshly installed my Deye SUN 800 and try to connect it to my home assistant instance. 
Periodically it looses the connection. In the tutorial I read:

"Check the version of the solarman logger. If the serial number starts with 17xxxxxxx or 21xxxxxxx (protocol V5), the component should work. If not, you may need to try the component for V4 of the protocol mentioned above." 

**My serial starts with 390**. What can I do? Which lookup_file: should I use? 🙂

Thank you!

**Comment by gejomo** [comment]
Hey guy’s,
I have the same problem. The serial number of my Deye logger starts with 417….

**Comment by prankousky** [comment]
Same here. Mine starts with `3914`.
