### ISSUE TITLE
Integration generates value change when value does not change

### ISSUE THREAD

**Issue by douglasfl** [StephanJoubert/home_assistant_solarman#24]
Hi, 
I'm using the integration, but every start of the day, the integration generates a value change that generates an invalid statistic.

In Energy, I have configured the XXX Total Production sensor, but every day the integration reports the value 0 at some point and then the accumulated production, but this generates an effect as if at that minute there was a change...

![image](https://user-images.githubusercontent.com/1014975/156631457-bf0ec607-3b80-4811-955d-b5ddc5b8ac4b.png)

![image](https://user-images.githubusercontent.com/1014975/156631544-5ba23c65-e102-472d-8b82-44a06de3b467.png)

sensor change history:
![image](https://user-images.githubusercontent.com/1014975/156631863-f6db84e4-607f-4336-86c5-d34c79ae76c4.png)

**Comment by StephanJoubert** [comment]
@douglasfl That spike is caused by the Energy Dashboard that tries to make sense of the first reading of the day. Try updating Home Assistant core and then see if the behavior is correct (there was change recently)
