### ISSUE TITLE
Missing deye_2mppt.yaml

### ISSUE THREAD

**Issue by skelks83** [StephanJoubert/home_assistant_solarman#254]
Hi,

i miss the file deye_2mppt.yaml. I have version 1.4.3. Installed and reloaded a few times. It's still missing, but it's in the repository.

![2023-03-27 16_26_43-Einstellungen – Home Assistant](https://user-images.githubusercontent.com/105865462/227969751-6c44ffe0-b18c-43ab-9bbe-544b680cc54b.png)

**Comment by skelks83** [comment]
I added the entry to the /solarman/const file and copied the deye_2mppt.yaml file as well. I was able to select the file now, but I don't get any readings. The status is N/A and Disconnected.

Could something else be missing? Another entry somewhere?

**Comment by qfinucane** [comment]
Great, Thanks for letting me know. :)

**Comment by m0d3rnX** [comment]
![image](https://user-images.githubusercontent.com/29262179/233831953-cf5d00c6-f1dc-44b7-a55c-447d4ffd21c4.png)

This happened to me too, fresh install of homeassistant, 
i will add i manually, just wanted you to know it's happening.
