### ISSUE TITLE
Strange Number

### ISSUE THREAD

**Issue by cyberrep** [StephanJoubert/home_assistant_solarman#31]
Dear guys, my serial start with 23xxxx I just add almost of all items and some of them is very strange. if anyone can help me I appreciate

the guys finish the instalation today, my model is belenergy 10

![solarman](https://user-images.githubusercontent.com/23341219/159927379-63a82c4e-1ceb-4e71-8f97-8c0658aceb83.PNG)

**Comment by StephanJoubert** [comment]
@cyberrep , the inverter almost certainly has different modbus registers to the DEYE inverter so you won't be able to use as is. If you can get the suppliers to send you the technical details containing the registers, we can accommodate it. The component is written in such a way as to quickly add other inverters via the lookup-file.

**Comment by cyberrep** [comment]
Perfect @StephanJoubert , I'll do!!! thanks a lot. Sorry for some dumb question, I'm tottaly new at this kind of stuff.

**Comment by cyberrep** [comment]
Good Morning @StephanJoubert , they send me this file, please check if it what you need.[https://we.tl/t-LpbuAcpZw7](url)

**Comment by cyberrep** [comment]
[Modbus-组串-微逆宁波德业V117(3).docx](https://github.com/StephanJoubert/home_assistant_solarman/files/8571910/Modbus-.-.V117.3.docx)

**Comment by StephanJoubert** [comment]
@cyberrep . This is perfect. I will send though my parser to generate a yaml file to start from. If you can then verify and tweak if needed, it can be included in future releases.

**Comment by cyberrep** [comment]
Sounds good, check what you need and I can do here. They will return to turn on my system definitely next week.

**Comment by cyberrep** [comment]
I use this json on nodered, and I can get some value as well, its a interesting tool to get values also


[{"id":"2b3c18a4.5e8a58","type":"subflow","name":"Sofar to MQTT","info":"","category":"","in":[{"x":60,"y":160,"wires":[{"id":"13d69aa3.9c4fc5"},{"id":"b4dc7f46.aec34"}]}],"out":[{"x":1140,"y":160,"wires":[{"id":"88063fab.1e103","port":0},{"id":"13d69aa3.9c4fc5","port":0}]}],"env":[{"name":"topic","type":"str","value":"KTL","ui":{"label":{"en-US":"MQTT subject"},"type":"input","opts":{"types":["str"]}}},{"name":"all","type":"bool","value":"true","ui":{"label":{"en-US":"All reg"},"type":"checkbox"}},{"name":"0","type":"bool","value":"true","ui":{"label":{"en-US":"Status"},"type":"checkbox"}},{"name":"1","type":"bool","value":"false","ui":{"label":{"en-US":"Err1"},"type":"checkbox"}},{"name":"2","type":"bool","value":"false","ui":{"label":{"en-US":"Err2"},"type":"checkbox"}},{"name":"3","type":"bool","value":"false","ui":{"label":{"en-US":"Err2"},"type":"checkbox"}}],"meta":{},"color":"#FFAAAA"},{"id":"8bee571f.9a6098","type":"function","z":"2b3c18a4.5e8a58","name":"KTL_Parser","func":"var ratio =[1,1,1,1,1,1,0.1,0.01,0.1,0.01,\n            10,10,10,10,0.01,0.1,0.01,0.1,0.01,0.1,\n            0.01,1,1,1,1,0.01,1,1,1,1,1,1,1,1,1,1,1,1,1,1];\nvar state =[\"Oczekiwanie\",\"Weryfikacja wewn.\",\"Normalny\",\"BLAD\",\"Permanent\"];\nvar data ='{\"data\":[';\n//  {\"data\":[{\"uuid\":\"\nvar val =0;\nvar Hi = 0;\nfor (i=0; i<=29 ; i++){\n    if (env.get('all')){   // if (env.get(i)){\n    data +='{\"id\":\"'+i.toString()+'\",\"values\":['    \n    switch(i) {\n     //  case 0:\n      ////    val = msg.payload[1]; \n      //    data +=state[val];\n      //  break; \n       case 21:\n         Hi = msg.payload[i*2]*256 +msg.payload[i*2+1];\n         i++;\n         val = msg.payload[i*2]*256 +msg.payload[i*2+1];\n         val += Hi*255;\n       break;\n       case 23:\n         Hi = msg.payload[i*2]*256 +msg.payload[i*2+1];\n         i++;\n         val = msg.payload[i*2]*256 +msg.payload[i*2+1];\n         val += Hi*255;\n        break;\n        default:\n          val = msg.payload[i*2]*256 +msg.payload[i*2+1];\n        }\n //  if (i!=0) {\n      val = val*ratio[i];    \n      data +=val.toFixed (2);\n //      }\n    data +=']},';\n    }\n}\n\nmsg.payload = data.slice(0,-1)+']}';  \nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":330,"y":200,"wires":[["4f69e5be.d5ac4c"]]},{"id":"4528032f.b51c1c","type":"split","z":"2b3c18a4.5e8a58","name":"","splt":"\\n","spltType":"str","arraySplt":1,"arraySpltType":"len","stream":false,"addname":"topic","x":830,"y":200,"wires":[["88063fab.1e103"]]},{"id":"187d1917.3a60e7","type":"change","z":"2b3c18a4.5e8a58","name":"","rules":[{"t":"move","p":"payload.data","pt":"msg","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":650,"y":200,"wires":[["4528032f.b51c1c"]]},{"id":"88063fab.1e103","type":"function","z":"2b3c18a4.5e8a58","name":"map ids to topics","func":"var topic =env.get('topic');\nvar idMap = {\n'0': topic+'/Status',\n'1': topic+'/Err1',\n'2': topic+'/Err2',\n'3': topic+'/Err3',\n'4': topic+'/Err4',\n'5': topic+'/Err5',\n'6': topic+'/V1',\n'7': topic+'/A1',\n'8': topic+'/V2',\n'9': topic+'/A2',\n'10': topic+'/P1',\n'11': topic+'/P2',\n'12': topic+'/Power_P',\n'13': topic+'/Power_Q',\n'14': topic+'/Freq',\n'15': topic+'/V_L1',\n'16': topic+'/A_L1',\n'17': topic+'/V_L2',\n'18': topic+'/A_L2',\n'19': topic+'/V_L3',\n'20': topic+'/A_L3',\n'21': topic+'/TotalEnergy',\n'23': topic+'/TotalTime',\n'25': topic+'/DayEnergy',\n'26': topic+'/DayTime',\n'27': topic+'/TempMod',\n'28': topic+'/TempInner',\n'29': topic+'/V_Bus'\n};\n\nmsg.topic = idMap[msg.payload.id];\nmsg.payload = msg.payload.values[0];\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":990,"y":200,"wires":[[]]},{"id":"4f69e5be.d5ac4c","type":"json","z":"2b3c18a4.5e8a58","name":"","property":"payload","action":"","pretty":false,"x":470,"y":200,"wires":[["187d1917.3a60e7"]]},{"id":"13d69aa3.9c4fc5","type":"function","z":"2b3c18a4.5e8a58","name":"Status","func":"msg.topic = env.get('topic')+ \"/status\"\nvar s = (msg.payload[1] /1);\nif (s===0) {msg.payload = \"Wait\"}\nif (s===1) {msg.payload = \"Check\"}\nif (s===2) {msg.payload = \"Normal\"}\nif (s===3) {msg.payload = \"Error\"}\nif (s===4) {msg.payload = \"Permanent\"}\nif (s===9) {msg.payload = \"No Connect\"}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":190,"y":160,"wires":[[]]},{"id":"b4dc7f46.aec34","type":"switch","z":"2b3c18a4.5e8a58","name":"","property":"payload[1]","propertyType":"msg","rules":[{"t":"neq","v":"9","vt":"num"}],"checkall":"true","repair":false,"outputs":1,"x":190,"y":200,"wires":[["8bee571f.9a6098"]]},{"id":"916e4fd2.13596","type":"subflow","name":"Sofar inverter","info":"","category":"","in":[{"x":80,"y":80,"wires":[{"id":"e811032c.4d431"}]}],"out":[{"x":600,"y":140,"wires":[{"id":"4f9bce54.66b91","port":0}]},{"x":600,"y":200,"wires":[{"id":"ad8991f0.c505c","port":0}]}],"env":[{"name":"IP","type":"str","value":"","ui":{"type":"input","opts":{"types":["str"]}}},{"name":"serial_nr","type":"num","value":"","ui":{"label":{"en-US":"Logger S\\N"},"type":"input","opts":{"types":["num"]}}},{"name":"s_reg","type":"num","value":"0","ui":{"label":{"en-US":"From Register (dec)"},"type":"input","opts":{"types":["num"]}}},{"name":"e_reg","type":"num","value":"39","ui":{"label":{"en-US":"To Register (dec)"},"type":"input","opts":{"types":["num"]}}}],"meta":{},"color":"#FFAAAA","inputLabels":["in"],"outputLabels":["data","status byte"],"icon":"node-red/status.svg"},{"id":"c43f4230.d1f43","type":"function","z":"916e4fd2.13596","name":"CRC16-modbus","func":"var CRCMaster = {\n    StringToCheck: \"\",\n    CleanedString: \"\",\n    CRCTableDNP: [],\n    init: function() {\n        this.CRCDNPInit();\n    },\n    CleanString: function(inputType) {\n        if (inputType == \"ASCII\") {\n            this.CleanedString = this.StringToCheck;\n        } else {\n            if (this.StringToCheck.match(/^[0-9A-F \\t]+$/gi) !== null) {\n                this.CleanedString = this._hexStringToString(this.StringToCheck.toUpperCase().replace(/[\\t ]/g, ''));\n            } else {\n                window.alert(\"String doesn't seem to be a valid Hex input.\");\n                return false;\n            }\n        }\n        return true;\n    },\n    CRCDNPInit: function() {\n        var i, j, crc, c;\n        for (i = 0; i < 256; i++) {\n            crc = 0;\n            c = i;\n            for (j = 0; j < 8; j++) {\n                if ((crc ^ c) & 0x0001) crc = (crc >> 1) ^ 0xA6BC;\n                else crc = crc >> 1;\n                c = c >> 1;\n            }\n            this.CRCTableDNP[i] = crc;\n        }\n    },\n    CRC16Modbus: function() {\n        var crc = 0xFFFF;\n        var str = this.CleanedString;\n        for (var pos = 0; pos < str.length; pos++) {\n            crc ^= str.charCodeAt(pos);\n            for (var i = 8; i !== 0; i--) {\n                if ((crc & 0x0001) !== 0) {\n                    crc >>= 1;\n                    crc ^= 0xA001;\n                } else\n                    crc >>= 1;\n            }\n        }\n        return crc;\n    },\n    _stringToBytes: function(str) {\n        var ch, st, re = [];\n        for (var i = 0; i < str.length; i++) {\n            ch = str.charCodeAt(i); // get char\n            st = []; // set up \"stack\"\n            do {\n                st.push(ch & 0xFF); // push byte to stack\n                ch = ch >> 8; // shift value down by 1 byte\n            }\n            while (ch);\n            // add stack contents to result\n            // done because chars have \"wrong\" endianness\n            re = re.concat(st.reverse());\n        }\n        // return an array of bytes\n        return re;\n    },\n    _hexStringToString: function(inputstr) {\n        var hex = inputstr.toString(); //force conversion\n        var str = '';\n        for (var i = 0; i < hex.length; i += 2)\n            str += String.fromCharCode(parseInt(hex.substr(i, 2), 16));\n        return str;\n    },\n    Calculate: function(str, inputType) {\n        this.StringToCheck = str;\n        if (this.CleanString(inputType)) {\n            crcinputcrc16modbus=this.CRC16Modbus().toString(16).toUpperCase();\n            crcinputcrc16modbus=crcinputcrc16modbus.substr(2) + crcinputcrc16modbus.substr(0, 2); //swap bytes\n   \n        }\n    }\n};\n\nCRCMaster.init();\n\nvar inputType = \"HEX\";\nvar crcinputcrc16modbus;\nvar crcinput = msg.payload;\ncrcinput = crcinput.slice(-12);\nCRCMaster.Calculate(crcinput, inputType);\n\nmsg.payload = msg.payload + crcinputcrc16modbus.toLowerCase();\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":360,"y":80,"wires":[["c648833b.f8547"]]},{"id":"e811032c.4d431","type":"function","z":"916e4fd2.13596","name":"Out_Frame","func":"var a_start = env.get(\"s_reg\"); //adres startowy rejestru\nvar a_end = env.get(\"e_reg\");   //adres końcowy bloku rejestów\nvar oFrame = \"a5170010450000\"; //start bytes \n\nSN = env.get(\"serial_nr\");\nvar hexSN  = SN.toString(16).toLowerCase();\n//seria No.\noFrame +=(hexSN[6]+hexSN[7]+hexSN[4]+hexSN[5]+hexSN[2]+hexSN[3]+hexSN[0]+hexSN[1]);\n//data field\noFrame +=\"020000000000000000000000000000\"\nvar businessfield=\"0103\"+('0000'+a_start.toString(16).toLowerCase()).slice(-4)+('0000'+(a_end-a_start+1).toString(16).toLowerCase()).slice(-4) ;\noFrame += businessfield;\nmsg.payload = oFrame;\nmsg.host = env.get(\"IP\");\nmsg.port = 8899;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":190,"y":80,"wires":[["c43f4230.d1f43"]]},{"id":"c648833b.f8547","type":"function","z":"916e4fd2.13596","name":"CRC frame","func":"var l = parseInt(msg.payload.length)/2;\nvar bFrame =[l+2]; \nvar crc = 0;\nbFrame[0] = parseInt((msg.payload[0]+msg.payload[1]),16); \nfor (i=1; i<l; i++){\n   bFrame[i] = parseInt((msg.payload[i*2]+msg.payload[(i*2)+1]),16);  \n   crc +=bFrame[i];\n   crc &= 255; \n}\nbFrame[i] = crc;\nbFrame[i+1] = 0x15;\nmsg.payload = Buffer.from(bFrame);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":530,"y":80,"wires":[["82c505a3.984848"]]},{"id":"82c505a3.984848","type":"tcp request","z":"916e4fd2.13596","server":"","port":"","out":"time","splitc":"100","name":"Sofar","x":170,"y":140,"wires":[["4b49d7fe.e74338"]]},{"id":"4f9bce54.66b91","type":"function","z":"916e4fd2.13596","name":"Response To Data ","func":"var l=2*(env.get(\"e_reg\")-env.get(\"s_reg\"))+6;\nmsg.payload = msg.payload.slice(-l,-4)\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":470,"y":140,"wires":[[]]},{"id":"4b49d7fe.e74338","type":"switch","z":"916e4fd2.13596","name":"","property":"payload[0]","propertyType":"msg","rules":[{"t":"eq","v":"0xA5","vt":"num"},{"t":"else"}],"checkall":"true","repair":false,"outputs":2,"x":290,"y":140,"wires":[["4f9bce54.66b91"],["ad8991f0.c505c"]]},{"id":"ad8991f0.c505c","type":"change","z":"916e4fd2.13596","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"[0,9]","tot":"bin"}],"action":"","property":"","from":"","to":"","reg":false,"x":470,"y":200,"wires":[[]]},{"id":"c0f67a1f.047d88","type":"tab","label":"Sofar_LAN","disabled":false,"info":""},{"id":"fcc6240b.4bea78","type":"subflow:916e4fd2.13596","z":"c0f67a1f.047d88","name":"KTL","env":[{"name":"IP","value":"192.168.0.110","type":"str"},{"name":"serial_nr","value":"2103273123","type":"num"},{"name":"e_reg","value":"29","type":"num"}],"x":390,"y":160,"wires":[["4c4314bd.2626ec"],[]]},{"id":"ab3a3144.a345a","type":"inject","z":"c0f67a1f.047d88","name":"","props":[{"p":"topic","vt":"str"}],"repeat":"30","crontab":"","once":false,"onceDelay":0.1,"topic":"time","x":130,"y":160,"wires":[["b5c4098e.0a9938"]]},{"id":"4c4314bd.2626ec","type":"subflow:2b3c18a4.5e8a58","z":"c0f67a1f.047d88","name":"","env":[{"name":"topic","value":"Sofar","type":"str"},{"name":"0","type":"bool","value":"false"}],"x":560,"y":160,"wires":[["56d38d7a.a9fe54"]]},{"id":"56d38d7a.a9fe54","type":"mqtt out","z":"c0f67a1f.047d88","name":"","topic":"","qos":"0","retain":"true","respTopic":"","contentType":"","userProps":"","correl":"","expiry":"","broker":"52029cdf.11e864","x":710,"y":160,"wires":[]},{"id":"1cddf4ce.872d2b","type":"sunrise","z":"c0f67a1f.047d88","name":"","lat":"50.98","lon":"17.22","start":"nauticalDawn","end":"nauticalDusk","soff":"0","eoff":"0","x":110,"y":100,"wires":[["b5c4098e.0a9938"],[]]},{"id":"b5c4098e.0a9938","type":"function","z":"c0f67a1f.047d88","name":"gate","func":"if (msg.topic == \"sun\"){\n    context.set(\"Day\", msg.payload);\n    return null;\n}\nif (msg.topic == \"time\"){\n    var gate = context.get(\"Day\") || 0;\n    if (gate ==1){\n        return msg;\n    }\n    else {\n      return null;  \n    }\n}\nreturn null;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":270,"y":160,"wires":[["fcc6240b.4bea78"]]},{"id":"52029cdf.11e864","type":"mqtt-broker","name":"","broker":"localhost","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]

**Comment by cyberrep** [comment]
this is the topic for curiosity


https://forum.arturhome.pl/t/sofar-solar-inwerter-odczyt-danych-bezposrednio-przez-fabryczny-datalogger/3180/203

**Comment by cyberrep** [comment]
> @cyberrep . This is perfect. I will send though my parser to generate a yaml file to start from. If you can then verify and tweak if needed, it can be included in future releases.

hey buddy, any news about this config?
