### ISSUE TITLE
deye_4mptt.yaml negative value from the day before in the statistic

### ISSUE THREAD

**Issue by OLLIBERTUS** [StephanJoubert/home_assistant_solarman#324]
Hello, I have implemented the Deye600 (two times) with 4mqtt.yaml and it works very good but after I import the "Dayli_Production" into the energy dashboard I got the negativ value from the day before in the graph (yellow/light yellow) at the beginning of the day (4:00am). Why it is like this and hoe can I fix this. After the inverter works everything is okay and it collect all the data very good.

There are still two additional shelly plugs (brown/light brown) working that's the reason that you see in summary four production values.

<img width="971" alt="Bildschirmfoto 2023-06-11 um 17 31 30" src="https://github.com/StephanJoubert/home_assistant_solarman/assets/136021088/b3a6ac05-7bc7-4779-b8a8-1aad5fbd5486">

**Comment by pascal-mar** [comment]
Hello, I had the same problem. If you take the total production it is displayed correctly. Greetings Pascal

**Comment by OLLIBERTUS** [comment]
Hello together, with support from the community from https://community.simon42.com I have solved the problem. I have add in the "Daily Production" at state_class: "total_increasing" and not only "total", and now it works......I can close the topic
![Bildschirmfoto 2023-06-12 um 22 00 54](https://github.com/StephanJoubert/home_assistant_solarman/assets/136021088/3253eb93-e8c3-439a-9ff4-6414d012a755)
![06138c7f40a_2_510x1000](https://github.com/StephanJoubert/home_assistant_solarman/assets/136021088/f5f7405d-743d-4356-96bf-316cc09b607c)
