### ISSUE TITLE
HA setup issues

### ISSUE THREAD

**Issue by oaktek** [StephanJoubert/home_assistant_solarman#40]
Hi @StephanJoubert, thanks so much for this integration! Wondering if you can help me as I cant figure this out and I have followed your instructions.

Firstly in configuration.yaml i have the following:

sensor:
  - platform: solarman
    name: DEYE 
    inverter_host: 192.168.2.2
    inverter_port: 8899
    inverter_serial: 23339##### ---- I haven taken out the rest of the serial for this post, newer version dont know if this is the problem 
    #inverter_mb_slaveid: 1 ------- had to comment this out otherwise the integration wont start
    scan_interval: 30
    lookup_file: deye_string.yaml

Then in the energy configuration I do not have the option you show in your screenshots, this is what i have:
<img width="290" alt="image" src="https://user-images.githubusercontent.com/68914405/163668887-58f48f5d-ad3f-4bfe-baca-aec553027d21.png">

Then when i do choose some options i have errors saying that last_reset is missing and I cant add the battery info:
<img width="997" alt="image" src="https://user-images.githubusercontent.com/68914405/163669050-7f60c292-0e21-483c-b716-dc821610a4a4.png">

This is what my energy dashboard looks like:
<img width="1648" alt="image" src="https://user-images.githubusercontent.com/68914405/163669109-4c28c252-212b-4417-81b1-f33ec15a2550.png">

This is the sensor info i have:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/68914405/163669135-87fdca1d-321b-4e27-9014-1d1214bcfc13.png">
<img width="356" alt="image" src="https://user-images.githubusercontent.com/68914405/163669174-daa5f8e7-fb2e-4f4a-beab-ce2b1f749a9d.png">
<img width="354" alt="image" src="https://user-images.githubusercontent.com/68914405/163669184-8edc60e6-7cd5-44e4-9929-40d67787b1de.png">

I would so appreciate your help!

**Comment by oaktek** [comment]
Hi, sorry found my main issue! I had to use the parameters.yaml and now im getting more info. Can you tell me if im missing anything or if anything is wrong?

Heres the list I now get in energy configuration:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/68914405/163671151-d104df58-7d2b-4064-aa5e-f41cde602a0b.png">
Last one being: Deye Total Production

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/68914405/163671180-2a83dd65-d754-42a2-946c-4952ea5173e9.png">
In the solar production im still getting that one paramter missing as you can see and in the batteries area i dont have the options you have

Below the energy dashboard and something doest seem right, you will see a photo of the inverter display
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/68914405/163671557-bb3174bb-f8f6-471f-830f-8e964eae824b.png">
![20220416_122703](https://user-images.githubusercontent.com/68914405/163671629-bb837cf0-3fbb-4647-a971-d539743b7ee6.jpg)
So you will see the solar production on Kw, the house usage and whats coming in from eskom (power company) doesnt seem right, also not too sure about the battery info

**Comment by pepelillo** [comment]
Not sure if this can help, but make sure that you put your CT clamp in the proper way (see doc)

**Comment by StephanJoubert** [comment]
@oaktek , I think you may have an older version of Home Assistant that requires the "last-reset" parameter. I had it in initially, but with the update they recommend that it be taken out. The dashboard is not 100% the same as the inverter screen since the Home Assistant dashboard shows a cumulative icon, and the inverter show it in real-time.

Let the dashboard collect info for a day and then see if the results look correct.

**Comment by midlakelands** [comment]
Hi,
I was having similar issues with the solis-hybrid parameters, after reading [the thread](https://community.home-assistant.io/t/home-energy-management-in-2021-8/325539/157) on it I decided to change some of the daily parameters but I did it with the following in configuration.yaml as that allowed me to experiment without changing the original files.  After an hour the stats started to work (I believe the energy card updates at 12 mins past each hour) 

homeassistant:
  customize:
    # Add an entry for each entity that you want to overwrite.
    sensor.solarman_daily_generation:
      state_class: total_increasing
    sensor.solarman_today_battery_discharge:
      state_class: total_increasing
    sensor.solarman_today_battery_charge:
      state_class: total_increasing

**Comment by dsgepers** [comment]
I've acctually been solving this by copying the configuration and adding an additional field:

``` 
    - name: "Daily Production"
      class: "energy"
      state_class: "total"      
      uom: "kWh"
      scale: 0.01
      rule: 1
      registers: [0x0019]
      icon: 'mdi:solar-power'   

    - name: "Daily Production (Total Increasing)"
      class: "energy"
      state_class: "total_increasing"      
      uom: "kWh"
      scale: 0.01
      rule: 1
      registers: [0x0019]
      icon: 'mdi:solar-power' 
``` 

Which is less than perfect, because this morning (after updating last night), no solar generation showed up in the dash and the custom property was gone. I think I might give @midlakelands solutions a try, that seems solid.

**Comment by CreateYourAccount-username** [comment]
I have the same issue with a Solis inverter. All the other things work fine, it's just adding it to the Energy dashboard that doesn't work due to the "Last reset missing
The following entities have state class 'measurement' but 'last_reset' is missing:
sensor.solarman_daily_generation" error.

I'm using solarman 1.4.1 and HA 2022.4.7

**Comment by midlakelands** [comment]
> I have the same issue with a Solis inverter. All the other things work fine, it's just adding it to the Energy dashboard that doesn't work due to the "Last reset missing The following entities have state class 'measurement' but 'last_reset' is missing: sensor.solarman_daily_generation" error.
> 
> I'm using solarman 1.4.1 and HA 2022.4.7

Try the solution i gave above (replacing your sensor name for daily generation and battery charge/discharge) it'll update the energy card in an hour or so. Alternatively you can update the original yaml file but I didn't bother change it. You will need to either restart HA or reload the customization yaml to see those updates.

The explanation for why I changed them to total_increasing is below
![image](https://user-images.githubusercontent.com/10165561/165551751-a1aa94a8-bab7-4f5b-b994-68ea34fe2191.png)

**Comment by CreateYourAccount-username** [comment]
> > I have the same issue with a Solis inverter. All the other things work fine, it's just adding it to the Energy dashboard that doesn't work due to the "Last reset missing The following entities have state class 'measurement' but 'last_reset' is missing: sensor.solarman_daily_generation" error.
> > I'm using solarman 1.4.1 and HA 2022.4.7
> 
> Try the solution i gave above (replacing your sensor name for daily generation and battery charge/discharge) it'll update the energy card in an hour or so. Alternatively you can update the original yaml file but I didn't bother change it. You will need to either restart HA or reload the customization yaml to see those updates.
> 
> The explanation for why I changed them to total_increasing is below ![image](https://user-images.githubusercontent.com/10165561/165551751-a1aa94a8-bab7-4f5b-b994-68ea34fe2191.png)

I have put those duplicate sensors in the solarman solis_hybrid yaml. I think it's working okay, slowly getting some results in. I'll see how it performs in the sunshine tomorrow. Thanks!
