### ISSUE TITLE
Bug in definition file

### ISSUE THREAD

**Issue by markodraca** [StephanJoubert/home_assistant_solarman#421]
Hi

There is a bug in definition file deye_sg04lp3.yaml

- name: "Total Energy Bought"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [0x020A,0x020B]
      icon: 'mdi:transmission-tower-export'
`

Rule should be 3.

**Comment by PV-Joe** [comment]
I changed it to rule 3 and restarted HA.

Total energy bought is still showing me the same different value as with rule 1 compared to the Solarman App.
