### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by admkhe** [StephanJoubert/home_assistant_solarman#423]
Hi,

When trying to add a solarman device, I get this:

![image](https://github.com/StephanJoubert/home_assistant_solarman/assets/146985108/49ac47e4-4a7e-4d5d-9951-6ed1423e4507)

That's even before filling in anything.

thanks in adv

**Comment by dj9717** [comment]
hello,
the same problem here too. 
Homeassistent 2023.10.3 [docker-compose](https://www.home-assistant.io/installation/linux#docker-compose)
Solarman Integration [1.5.1](https://github.com/StephanJoubert/home_assistant_solarman/releases/tag/1.5.1)
please for support
gg

**Comment by jweea** [comment]
Try change it back
#https://github.com/StephanJoubert/home_assistant_solarman/commit/a1a5de42f1033b7a0403ad4581ba6fe4b90f6e36#diff-bbed67ea80599e4ac504d7f56d3475b028def737c2fd65a11d3aad364fc1711dL8-L14

**Comment by KoblerS** [comment]
unfortunately I do receive the same error, does anyone got a solution for this?

**Comment by asgaardwro** [comment]
got the same error :(

**Comment by chrisvanmeer** [comment]
That solved my issue.
