### ISSUE TITLE
Model No: SUN-12K-SG04LP3-EU

### ISSUE THREAD

**Issue by adiweps** [StephanJoubert/home_assistant_solarman#434]
Good day,

I have a Deye 12kva Hybrid Inverter that has a serial number starting with 27xxxxx

I am not able to get accurate or any readings when using the Solarman integration with Home Assistant.

Any suggestions on what to do / try?

Using the deye_hybrid.yaml on the latest version.

**Comment by PV-Joe** [comment]
Try the deye_sg04lp3.yaml

**Comment by adiweps** [comment]
That worked, thank you
