### ISSUE TITLE
Microinverter VESDAS/DEYE SUN2000G3 (new config)

### ISSUE THREAD

**Issue by chipsi** [StephanJoubert/home_assistant_solarman#46]
Hello.
I made a new YAML file for the new DEYE / VESDAS SUN2000G3 microinverter. It has 4x MPPT and 4x inverter. This is only the first version. Maybe it will help someone.
Thank you to the author for a great job and other beautiful energy day.
ChipSi007

.txt rename to .yaml
[deye_4mppt.txt](https://github.com/StephanJoubert/home_assistant_solarman/files/8664097/deye_4mppt.txt)

**Comment by tcwed-br** [comment]
> Hello. I made a new YAML file for the new DEYE / VESDAS SUN2000G3 microinverter. It has 4x MPPT and 4x inverter. This is only the first version. Maybe it will help someone. Thank you to the author for a great job and other beautiful energy day. ChipSi007
> 
> .txt rename to .yaml [deye_4mppt.txt](https://github.com/StephanJoubert/home_assistant_solarman/files/8664097/deye_4mppt.txt)

Hello Stephan / Chipsi 
great job  4pcs DeyeSun1600 now working in HA ... trying to figure out how to get the "radiator temperature" out of the box ...
many thanks and keep on going

**Comment by chipsi** [comment]
Hello.
I am trying it too, but it return zero. I'll let you know when I find it.

**Comment by chipsi** [comment]
I have got it. Add this

      - name: "Radiator temperature"
        class: "temperature"
        state_class: "measurement"
        uom: "°C"
        scale: 0.01
        rule: 1
        registers: [0x005A]
        icon: "mdi:thermometer"

**Comment by tcwed-br** [comment]
Hello 
will need to copy 4mppt.yaml to the correct path 
and use the device serial number ( not inverter serial ) 
config.yaml 
platform: solarman  
name: DEYExyz
inverter_host: 192.168.xx.yy
inverter_port: 8899  
inverter_serial: 4041xxxxx
inverter_mb_slaveid: 1  
lookup_file: deye_4mppt.yaml
...
ps radiator temperature works thanks chipsi

**Comment by wmjv** [comment]
Thanks! It worked!

**Comment by StephanJoubert** [comment]
Hi @chipsi. Thanks for the good work. I have pulled onto the main branch and it will be added to the next release of the component. Keep well!

**Comment by alessandroo23** [comment]
Chipsi, Leonardolisboa, Tcwed-br, Thanks! It worked. data is now being collected.

**Comment by VaillantHassIo** [comment]
this works for Bosswerk MI600 ( OEM ) as well

**Comment by giovanne123** [comment]
for at least Bosswerk MI600 you can also add for Daily/Total per Modul (example is for the 2 Mppt of the Bosswerk). 
Using it on my HA/Solarman intergration already
```

- name: "Daily Production PV1"
class: "energy"
state_class: "total"
uom: "kWh"
scale: 0.1
rule: 1
registers: [0x0041]
icon: 'mdi:solar-power'


- name: "Daily Production PV2"
class: "energy"
state_class: "total"
uom: "kWh"
scale: 0.1
rule: 1
registers: [0x0042]
icon: 'mdi:solar-power'


- name: "Total Production PV1"
class: "energy"
state_class: "total_increasing"
uom: "kWh"
scale: 0.1
rule: 3
registers: [0x0045,0x0046]
icon: 'mdi:solar-power'


- name: "Total Production PV2"
class: "energy"
state_class: "total_increasing"
uom: "kWh"
scale: 0.1
rule: 3
registers: [0x0047,0x0048]
icon: 'mdi:solar-power'
```
