### ISSUE TITLE
Not working with 2024.02

### ISSUE THREAD

**Issue by paolo-desalvo** [StephanJoubert/home_assistant_solarman#513]
Logger: homeassistant.setup
Source: setup.py:404
First occurred: 09:24:53 (1 occurrences)
Last logged: 09:24:53

Unable to prepare setup for platform 'solarman.sensor': Platform not found (No module named 'pysolarmanv5').

**Comment by paolo-desalvo** [comment]
Fixed .. installed the required module.

pip install pysolarmanv5

**Comment by paolo-desalvo** [comment]
Closed

**Comment by nandogandra** [comment]
> Fixed .. installed the required module.
> 
> pip install pysolarmanv5

Hi man. can you give us a step-by-step procedure on how to install this on home assistant ?
