### ISSUE TITLE
Monthly Generation always 0 using Solis Hybrid template

### ISSUE THREAD

**Issue by LucidityCrash** [StephanJoubert/home_assistant_solarman#56]
https://github.com/StephanJoubert/home_assistant_solarman/blob/f6180580d922941903699d1a1fc3215936aaba76/custom_components/solarman/inverter_definitions/solis_hybrid.yaml#L278

Think this line should be 

`registers: [33032,33031]`

**Comment by viking2010** [comment]
Funny you should log that, I've just altered the solis_hybrid.yaml file to the same registers as you and it's now reporting the correct figures!
