### ISSUE TITLE
Deye SUN20K

### ISSUE THREAD

**Issue by Saurman** [StephanJoubert/home_assistant_solarman#566]
I have Deye SUN20K inverter running wifi logger version LSW3_32U_5406_1.06. Tried all the possible configurations, it gives either unknown value or some weird numbers

**Comment by Nick-Most** [comment]
Hi, I have tested on the same firmware "Current version:LSW3_32U_5406_1.06" with DEYE SUN-6K-SG03-LP1-EU and it works.

**Comment by Saurman** [comment]
fixed by switching to killerza
