### ISSUE TITLE
Solis 3P6K 4G not working

### ISSUE THREAD

**Issue by Kuchiru** [StephanJoubert/home_assistant_solarman#582]
Hi there,

I have a Solis 3P6K 4G with a WiFi stick connected to my network.
The serial number is 404980XXXX and the firmware MW_08_512_0501_1.82

When i add the device with the following config:
<img width="402" alt="image" src="https://github.com/StephanJoubert/home_assistant_solarman/assets/7408353/39ece9ea-09a2-4fd4-ae56-f8f6c7392107">

I'm unfortunately met with the following log entry:
` Querying [4999 - 4999] failed with exception [IllegalDataAddressError: The data address received in the request is not an allowable address for the server. ] `

All entities are unknown and the connection state is disconnected.

I'm not sure how to continue from here and any help is appreciated.

**Comment by Kuchiru** [comment]
@agirilovich i see you committed the yaml for this device, would you have any pointers for me?

**Comment by agirilovich** [comment]
Yeah. Suddenly reading of 4999 register got breakable.
I didn't investigate it deeply. But here is hotfix [remove 4999 register request](https://github.com/StephanJoubert/home_assistant_solarman/commit/ff30b215532e5821510cb176773be82d950edd07) available.

Obviously, you are using old version of component. Just update it.
