### ISSUE TITLE
Missing DC Power in deye_2mppt.yaml

### ISSUE THREAD

**Issue by NikromHD** [StephanJoubert/home_assistant_solarman#583]
Hallo ich hab eine Frage.

Und zwar sind in Solarman auch die DC Power Leistungen hinterlegt.
Diese würde ich ebenfalls gerne in Homeassistent angezeigt bekommen.
Bei mir läuft die deye_2mppt.yaml einwandfrei

Ich habe aus der deye_hybrid.yaml die die Werte Register felder übernommen. Jedoch bekomme ich dann nur unbekannt angezeigt.

Kann mir jemand die Registers für die Werte nennen ?

Ich würde gerne auswerten wie Ost/West sich verhalten.

-----------------------------------------------------------------------------------------------------------------------------

Hello, I have a question.

The DC power outputs are also stored in Solarman.
I would also like to have these displayed in Home Assistant.
The deye_2mppt.yaml works perfectly for me

I have transferred the values of the register fields from deye_hybrid.yaml. However, I then only get unknown.

Can someone tell me the registers for the values?

I would like to evaluate how east/west behave.

![57acb9fbdd6dff51849e02b2c144ff4abcaeace8_2_224x500](https://github.com/StephanJoubert/home_assistant_solarman/assets/167187102/e1d0d1d4-3086-48ed-824c-16506d45707c)
![82b71e3e4b54bf490115e4c278ccb9648cd242c8_2_224x500](https://github.com/StephanJoubert/home_assistant_solarman/assets/167187102/b7339dc5-827a-45ac-94aa-60362c58de16)

Viele Grüße
Nikrom

**Comment by githubDante** [comment]
It appears  that the values are calculated from Voltage * Current for the respective string. There are no register definitions for them.

**Comment by NikromHD** [comment]
Thanks for the Info.

I solved this with an Helper
I created a template with the code
`{{ (states('sensor.west_ost_pv2_voltage') | float *
    states('sensor.west_ost_pv2_current') | float)| round(2) }}`

Its Look like this 
![Screenshot_20240522-221428](https://github.com/StephanJoubert/home_assistant_solarman/assets/167187102/4b139ab9-b509-4f27-ace7-47be6c67154d)

And a second template Helper for pv1 with Same Code
