### ISSUE TITLE
Havells inverter (rebranded sofar) 

### ISSUE THREAD

**Issue by amansarroha** [StephanJoubert/home_assistant_solarman#607]
My logger serial  number starts from 29xxxxx, I have tried everything from downgrading to 1.4.3, tried evert yaml config. I alwats get querying registers failed, aborting.

**Comment by sofkaski** [comment]
Is this a new integration or has this been working and now stopped working? Debug log around the point where 'querying registers failed' occurs would give more hints what might be wrong.
