### ISSUE TITLE
Add Power Value for PV n calculated by voltage and current

### ISSUE THREAD

**Issue by basti122303** [StephanJoubert/home_assistant_solarman#665]
Hello,
I have add my Deye Sun 600 (deye_2mppt.yaml) to HA and want to see Power Values per string.
Is there a way to calculate this values or add custom sensors that can do that?

Best regards,

**Comment by davidrapan** [comment]
Hi @basti122303, this feature exists in [my integration](https://github.com/davidrapan/ha-solarman) for quite some time. 😉
