### ISSUE TITLE
SUN-M200G4-EU-Q0

### ISSUE THREAD

**Issue by aichingerk** [StephanJoubert/home_assistant_solarman#684]
Hi, the standard deye_4mppt.yaml doesn't work with this new device. Did anyone have a correct yaml file for me, that i can implement the microconverter SUN-M200G4-EU-Q0 to home assistant.

The firmware is: MW3_16U_5406_1.62

**Comment by davidrapan** [comment]
Hi @aichingerk, it has to work, as mentioned by one of the users of my integration (using profile with same registers) here: https://github.com/davidrapan/ha-solarman/issues/84#issuecomment-2431352888

**Comment by aichingerk** [comment]
Thx, today i have installed your implementation [from davidrapan](https://github.com/davidrapan/ha-solarman) and i can connect to the microconverter. 
Thank you very much for this hint.

**Comment by aichingerk** [comment]
close it here
